lunch = {
    "header": "Persona 4 Perfect Boxed Lunch Combinations",
    "data": [
        "Broiled Fish: Wrap it tightly (Yukiko)",
        "California Rolls: Mix and cool simultaneously (Naoto)",
        "Carrot & Burdock Root Kinpira: Add Soy Sauce and Mirin (Yumi)",
        "Chakin Sushi: Thinned Eggs (Rise)",
        "Cream Stew: Dump in all the cold Milk (Rise) - 1/26",
        "Croquettes Curry: High Simmer",
        "Daigaku-Imo: Deep Fry (Yukiko, Music, or Ai) - 7/6",
        "Fried Chicken: Potato Starch (Unknown - Naoki? Daisuke? Chie?)",
        "Ginger Pork: Score with a Knife (Yosuke, Chie, Daisuke, Kou) - 4/25",
        "Grilled Fish: Strong Heat, from a distance",
        "Gyoza: Olive Oil - 1/10",
        "Hamburgers: Cut a hole and look for Juice - 6/29",
        "Kakuni: Mirin, Sugar & Sake (10/2)",
        "Marinated Spinach: Strain it (Rise)",
        "Long-Simmered Meat Stew (Beef Stew): Simmer with a Dropped Lid (Yosuke, Chie, Kou)",
        "Mentaiko Pasta: Mayonnaise (Naoto) - 1/16",
        "Oden: Keep on a Low Flame, Don't Boil (Yosuke)",
        "Potato Salad: Smash while still hot (Yukiko? Yosuke + Chie) - 6/12",
        "Pudding: Vanilla extract (Kanji, Ai, Ayane, Ai - 7/12)",
        "Sweet & Sour Pork: Potato Starch",
        "Tonkatsu: Flour, Egg, than Panko",
        "Vichyssoise: Add lots of Milk",
        "Yakiniku Bento: Use Soy Sauce (Chie)"
    ],
    "dates_header": "Some dates when lunch is available (incomplete)",
    "dates_data": ["April 25 (Ginger Pork)", "May 12", "May 31", "June 12 (Potato Salad)",
                   "July 6(Daigaku-Imo)", "July 12 (Pudding)", "July 14 (Potato Salad)", "September 4",
                   "September 11 (Marinated Spinach?)", "September 21 (Tonkatsu?)", "September 26(Kakuni?)",
                   "September 29 (Croquettes)", "October 2 (Kakuni)", "October 25", "November 1",
                   "January 11 (1/12?)", "Jan 16 Mentaiko Pasta", "Jan 26 (Cream Stew, Rise)",
                   "Feb 1 (Broiled Fish)"]
}
